# Create Simple dir storage
- name: Check the storage
  shell: "lxc storage list | grep \" {{ storage.name }} \"; echo -n"
  register: sto_list
- name: debug sto_list
  debug:
    var: sto_list
# Create the storage only if it doesn't exist
- name: Create DIR storage
  command: "lxc storage create {{ storage.name }} dir"
  when: sto_list.stdout == ""
